import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-withholding-tax-reclaim",
  "engine": "recovery",
  "title": "Cross-Border Withholding Tax Reclaim",
  "shortTitle": "Cross-Border Withholding Tax Reclaim",
  "tagline": "Quantify, recover, and prevent financial leakage through cross-border withholding tax reclaim",
  "industry": "Investment Tax Recovery",
  "uiPort": 4633,
  "apiPort": 5633,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Cross-Border Withholding Tax Reclaim converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "receivedRefund",
    "expectedKey": "eligibleRefund",
    "actualLabel": "Received Tax Reclaim",
    "expectedLabel": "Treaty-Supported Reclaim",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Cross-Border Withholding Tax Reclaim evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("investor-beneficial-owner-registry","WTR01","Investor beneficial owner registry","Execute investor beneficial owner registry using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed investor beneficial owner registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Investor beneficial owner registry Reference","text","WTR01-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("custodian-account-mapping","WTR02","Custodian account mapping","Execute custodian account mapping using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed custodian account mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Custodian account mapping Reference","text","WTR02-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("security-income-event-ingestion","WTR03","Security income event ingestion","Execute security income event ingestion using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed security income event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Security income event ingestion Reference","text","WTR03-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("treaty-rate-library","WTR04","Treaty rate library","Execute treaty rate library using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed treaty rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Treaty rate library Reference","text","WTR04-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("statutory-treaty-calculation","WTR05","Statutory treaty calculation","Execute statutory treaty calculation using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed statutory treaty calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Statutory treaty calculation Reference","text","WTR05-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("relief-at-source-validation","WTR06","Relief-at-source validation","Execute relief-at-source validation using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed relief-at-source validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Relief-at-source validation Reference","text","WTR06-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("excess-withholding-detection","WTR07","Excess withholding detection","Execute excess withholding detection using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed excess withholding detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Excess withholding detection Reference","text","WTR07-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("tax-residency-evidence","WTR08","Tax residency evidence","Execute tax residency evidence using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed tax residency evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Tax residency evidence Reference","text","WTR08-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("power-of-attorney-control","WTR09","Power-of-attorney control","Execute power-of-attorney control using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed power-of-attorney control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Power-of-attorney control Reference","text","WTR09-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("market-filing-deadlines","WTR10","Market filing deadlines","Execute market filing deadlines using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed market filing deadlines decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Market filing deadlines Reference","text","WTR10-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("custodian-submission-workflow","WTR11","Custodian submission workflow","Execute custodian submission workflow using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed custodian submission workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Custodian submission workflow Reference","text","WTR11-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("tax-authority-queries","WTR12","Tax authority queries","Execute tax authority queries using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed tax authority queries decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Tax authority queries Reference","text","WTR12-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("refund-tracking","WTR13","Refund tracking","Execute refund tracking using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed refund tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Refund tracking Reference","text","WTR13-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("currency-reconciliation","WTR14","Currency reconciliation","Execute currency reconciliation using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed currency reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Currency reconciliation Reference","text","WTR14-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]}),
feature("country-custodian-analytics","WTR15","Country custodian analytics","Execute country custodian analytics using investors, beneficial owners, custodians, securities, income events, statutory and treaty rates, relief at source, residency evidence, forms, powers of attorney, deadlines, submissions, and refunds.","Produce a governed country custodian analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Custodian Account","text","Investor / Custodian Account · Standard Case"],["caseReference","Country custodian analytics Reference","text","WTR15-2026-001"],["receivedRefund","Received Tax Reclaim","currency",1197000],["eligibleRefund","Treaty-Supported Reclaim","currency",1412460],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Investor beneficial owner registry case","Custodian account mapping case","Security income event ingestion case","Treaty rate library case","Statutory treaty calculation case"]})
]);
