import React,{useEffect,useMemo,useState} from 'react';

const TOKEN='domain_recovery_token';
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(localStorage.getItem(TOKEN)?{Authorization:`Bearer ${localStorage.getItem(TOKEN)}`}:{}) ,...(options.headers||{})}});const text=await response.text();let data={};try{data=text?JSON.parse(text):{};}catch{throw new Error(`Server returned an invalid response (${response.status})`);}if(!response.ok){const error=new Error(data.error||`Request failed (${response.status})`);error.status=response.status;throw error;}return data;}
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value||0));
const titleCase=value=>String(value||'').replace(/_/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/\b\w/g,c=>c.toUpperCase());

function Login({health,onLogin}){
  const[form,setForm]=useState({email:'',password:''});const[accounts,setAccounts]=useState([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  useEffect(()=>{api('/api/auth/demo-credentials').then(data=>{setAccounts(data.accounts);setForm({email:data.email,password:data.password});}).catch(()=>{});},[]);
  async function submit(event){event.preventDefault();setBusy(true);setError('');try{const data=await api('/api/auth/login',{method:'POST',body:JSON.stringify(form)});localStorage.setItem(TOKEN,data.token);onLogin();}catch(e){setError(e.message);}finally{setBusy(false);}}
  function fill(account){if(!account)return;setError('');setForm({email:account.email,password:account.password});}
  return <div className="loginPage"><section className="loginStory"><span className="eyebrow">{health?.industry||'Domain recovery intelligence'}</span><h1>{health?.title||'Loading workspace…'}</h1><p>Convert operational evidence into governed decisions, recoverable value, and measurable outcomes.</p><div className="loginSignals"><div><strong>PostgreSQL</strong><span>Operational system of record</span></div><div><strong>OpenRouter</strong><span>Professional decision support</span></div><div><strong>Human governed</strong><span>Every decision retained</span></div></div></section><form className="loginCard" onSubmit={submit}><span className="eyebrow">Secure local demonstration</span><h2>Sign in to operations</h2><p>Fill the administrator credentials with one click, or choose another provisioned role.</p>{error&&<div className="error">{error}</div>}<button type="button" className="credentialButton" disabled={!accounts.length} onClick={()=>fill(accounts[0])}><span>Demo access</span><strong>Auto Fill Demo Credentials</strong><small>runtime-admin@example.com</small></button><div className="accountGrid">{accounts.map(account=><button type="button" className="account" key={account.email} onClick={()=>fill(account)}><strong>{account.name}</strong><span>Use {account.role} credentials</span></button>)}</div><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="primary wide" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><small>{health?.ai?.configured?'OpenRouter is configured.':'Deterministic calculations work locally; OpenRouter requires a configured key.'}</small></form></div>;
}
function Metric({label,value,detail}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>}
function PageTitle({kicker,title,subtitle,actions}){return <header className="pageTitle"><div><span className="eyebrow">{kicker}</span><h2>{title}</h2><p>{subtitle}</p></div>{actions&&<div className="buttonRow">{actions}</div>}</header>}
function Risk({value}){return <span className={`risk risk-${String(value).toLowerCase()}`}>{value}</span>}
function Empty({text}){return <div className="empty"><strong>No records found</strong><span>{text}</span></div>}

function Dashboard({app,data,onOpen}){
  return <><PageTitle kicker="Executive command center" title={app.title} subtitle={app.tagline}/><div className="hero"><div><span className="eyebrow">Primary measurable outcome</span><h3>{app.primaryOutcome}</h3><p>{app.valueNarrative}</p></div><strong>{money(data.totals.value)}</strong></div><div className="metrics"><Metric label="Domain capabilities" value={app.features.length}/><Metric label="Seeded operational records" value={data.totals.records}/><Metric label="Items requiring attention" value={data.totals.attention}/><Metric label="Represented financial value" value={money(data.totals.value)}/></div><section className="featureGrid">{data.features.map(feature=><button className="featureCard" key={feature.id} onClick={()=>onOpen(feature.id)}><div><span className="code">{feature.code}</span><Risk value={feature.high_risk? 'High':'Low'}/></div><h3>{feature.title}</h3><p>{feature.description}</p><footer><span>{feature.records} records</span><strong>{money(feature.value)}</strong></footer></button>)}</section></>;
}
function Field({field,value,onChange}){const common={value:value??'',onChange:e=>onChange(e.target.value),required:field.required};return <label>{field.label}{field.type==='select'?<select {...common}><option value="">Select…</option>{field.options.map(x=><option key={x}>{x}</option>)}</select>:field.type==='textarea'?<textarea {...common} rows="4"/>:<input {...common} type={['number','currency'].includes(field.type)?'number':field.type||'text'} step={field.type==='currency'?'0.01':undefined}/>}<small>{field.help||field.outcome}</small></label>}
function scenario(feature,type){return Object.fromEntries(feature.fields.map(field=>{let value=field[type]??field.sample??'';if(type==='high'&&typeof value==='number'&&!field.high)value=Math.round(value*2.75*100)/100;if(type==='exception'&&typeof value==='number'&&!field.exception)value=Math.round(value*.43*100)/100;if(field.type==='select'&&!field[type])value=field.options[type==='high'?Math.min(1,field.options.length-1):type==='exception'?Math.min(2,field.options.length-1):0];return[field.key,value];}));}
function Result({result}){if(!result)return null;return <section className="result"><div className="resultHead"><div><span className="eyebrow">{result.provider} · {result.model}</span><h3>{result.headline}</h3></div><div><Risk value={result.risk}/><strong>{result.confidence}% confidence</strong></div></div><p className="summary">{result.executiveSummary}</p><div className="resultMetrics">{result.metrics.map((m,i)=><Metric key={i} label={m.label} value={m.value}/>)}</div><div className="sections">{result.sections.map((s,i)=><article key={i}><h4>{s.title}</h4><p>{s.detail}</p></article>)}</div><div className="actions"><h4>Recommended actions</h4>{result.actions.map((a,i)=><div key={i}><span>{i+1}</span><p>{a}</p></div>)}</div><small className="disclaimer">{result.disclaimer}</small></section>}
function RecordModal({feature,item,onClose,onTransition}){return <div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal"><button className="close" onClick={onClose}>×</button><span className="eyebrow">{item.reference}</span><h2>{item.title}</h2><div className="metrics compact"><Metric label="Status" value={item.status}/><Metric label="Owner" value={item.owner}/><Metric label="Risk" value={item.risk}/><Metric label="Value" value={money(item.amount)}/></div><div className="detailGrid">{feature.fields.map(field=><div key={field.key}><span>{field.label}</span><strong>{String(item.payload[field.key]??'—')}</strong></div>)}</div><h4>Advance governed workflow</h4><div className="buttonRow">{['Investigating','Review','Approved','Closed'].map(status=><button className="secondary" key={status} onClick={()=>onTransition(status)}>{status}</button>)}</div></section></div>}
function Feature({app,feature,notify}){
  const[values,setValues]=useState(()=>scenario(feature,'standard'));const[items,setItems]=useState([]);const[result,setResult]=useState(null);const[selected,setSelected]=useState(null);const[busy,setBusy]=useState('');
  async function load(){setItems((await api(`/api/features/${feature.id}/records`)).items);}useEffect(()=>{setValues(scenario(feature,'standard'));setResult(null);setSelected(null);load();},[feature.id]);
  async function run(kind){setBusy(kind);try{const data=await api(`/api/features/${feature.id}/${kind}`,{method:'POST',body:JSON.stringify({values,analysisType:kind==='analyze'?'executive-risk-and-value':'calculation'})});setResult(data.result);}catch(e){notify(e.message,'error');}finally{setBusy('');}}
  async function create(event){event.preventDefault();setBusy('create');try{const data=await api(`/api/features/${feature.id}/records`,{method:'POST',body:JSON.stringify({values})});notify(data.message);await load();}catch(e){notify(e.message,'error');}finally{setBusy('');}}
  async function transition(status){try{const data=await api(`/api/features/${feature.id}/records/${selected.id}/transition`,{method:'POST',body:JSON.stringify({status})});notify(data.message);setSelected(data.item);await load();}catch(e){notify(e.message,'error');}}
  return <><PageTitle kicker={feature.code} title={feature.title} subtitle={feature.description}/><div className="outcome"><strong>Outcome</strong><span>{feature.outcome}</span></div><div className="workbench"><form className="panel" onSubmit={create}><div className="moduleTitle"><div><h3>Domain input workbench</h3><p>Use a realistic case, edit any field, then calculate or request AI decision support.</p></div></div><div className="scenarioRow"><button type="button" onClick={()=>setValues(scenario(feature,'standard'))}>Fill Standard Case</button><button type="button" onClick={()=>setValues(scenario(feature,'high'))}>Fill High-Risk Case</button><button type="button" onClick={()=>setValues(scenario(feature,'exception'))}>Fill Exception Case</button><button type="button" onClick={()=>setValues({})}>Clear All Fields</button></div><div className="formGrid">{feature.fields.map(field=><Field key={field.key} field={field} value={values[field.key]} onChange={value=>setValues({...values,[field.key]:value})}/>)}</div><div className="buttonRow"><button type="button" className="primary" onClick={()=>run('calculate')} disabled={!!busy}>{busy==='calculate'?'Calculating…':feature.calculateLabel}</button><button type="button" className="aiButton" onClick={()=>run('analyze')} disabled={!!busy}>{busy==='analyze'?'Analyzing with OpenRouter…':'Generate AI Decision Brief'}</button><button className="secondary" disabled={!!busy}>{busy==='create'?'Creating…':'Create Operational Case'}</button></div></form><Result result={result}/></div><section className="panel"><div className="moduleTitle"><div><h3>{feature.registerTitle}</h3><p>Click a row to inspect evidence and advance its governed state.</p></div><span className="badge">{items.length} PostgreSQL records</span></div>{items.length?<div className="tableWrap"><table><thead><tr><th>Reference</th><th>Case</th><th>Status</th><th>Owner</th><th>Risk</th><th>Due</th><th>Value</th></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>setSelected(item)}><td>{item.reference}</td><td>{item.title}</td><td>{item.status}</td><td>{item.owner}</td><td><Risk value={item.risk}/></td><td>{String(item.due_date).slice(0,10)}</td><td>{money(item.amount)}</td></tr>)}</tbody></table></div>:<Empty text="Create a case using the domain input workbench."/>}</section>{selected&&<RecordModal feature={feature} item={selected} onClose={()=>setSelected(null)} onTransition={transition}/>}</>;
}
function Analytics({app,onOpen}){const[data,setData]=useState(null);useEffect(()=>{api('/api/analytics').then(setData);},[]);if(!data)return <p>Loading analytics…</p>;const total=data.modules.reduce((sum,x)=>sum+Number(x.value||0),0);return <><PageTitle kicker="Outcome measurement" title="Recovery and compliance analytics" subtitle={app.primaryOutcome}/><div className="metrics"><Metric label="Portfolio value" value={money(total)}/><Metric label="Operational records" value={data.modules.reduce((s,x)=>s+x.records,0)}/><Metric label="High-risk records" value={data.modules.reduce((s,x)=>s+x.high_risk,0)}/><Metric label="Closed outcomes" value={data.modules.reduce((s,x)=>s+x.closed,0)}/></div><section className="panel analyticsList">{data.modules.map(module=><button key={module.id} onClick={()=>onOpen(module.id)}><div><strong>{module.title}</strong><span>{module.records} records · {module.high_risk} high risk · {module.closed} closed</span></div><strong>{money(module.value)}</strong></button>)}</section></>}
function Audit(){const[items,setItems]=useState([]);const[selected,setSelected]=useState(null);useEffect(()=>{api('/api/audit-events').then(data=>setItems(data.items));},[]);return <><PageTitle kicker="Governance" title="Decision audit trail" subtitle="Every creation, transition, calculation, and AI analysis remains attributable."/><div className="tableWrap"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Object</th><th>Reference</th><th>Detail</th></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>setSelected(item)}><td>{new Date(item.event_time).toLocaleString()}</td><td>{item.actor}</td><td>{item.action}</td><td>{item.object_type}</td><td>{item.object_reference}</td><td>{item.detail}</td></tr>)}</tbody></table></div>{selected&&<div className="modalBack" onClick={()=>setSelected(null)}><section className="modal"><button className="close">×</button><h2>{selected.action} · {selected.object_reference}</h2><div className="detailGrid">{Object.entries(selected).map(([k,v])=><div key={k}><span>{titleCase(k)}</span><strong>{String(v)}</strong></div>)}</div></section></div>}</>}

export default function App(){
  const[health,setHealth]=useState(null);const[app,setApp]=useState(null);const[data,setData]=useState(null);const[page,setPage]=useState('dashboard');const[notice,setNotice]=useState(null);
  async function load(){try{const [a,d]=await Promise.all([api('/api/app'),api('/api/dashboard')]);setApp(a);setData(d);document.documentElement.style.setProperty('--accent',a.accent);}catch(e){if(e.status===401){localStorage.removeItem(TOKEN);setApp(null);}}}
  useEffect(()=>{api('/api/health').then(setHealth);if(localStorage.getItem(TOKEN))load();},[]);
  function notify(message,type='success'){setNotice({message,type});setTimeout(()=>setNotice(null),5000);}
  function openFeature(id){setPage(`feature:${id}`);}
  if(!app)return <Login health={health} onLogin={load}/>;
  const featureId=page.startsWith('feature:')?page.slice(8):null;const feature=app.features.find(x=>x.id===featureId);const nav=[{id:'dashboard',label:'Executive Overview'},{id:'analytics',label:'Outcome Analytics'},...app.features.map(f=>({id:`feature:${f.id}`,label:f.title})),{id:'audit',label:'Decision Audit Trail'}];
  return <div className="shell"><aside><div className="brand"><span className="eyebrow">{app.industry}</span><h1>{app.shortTitle}</h1><p>{app.primaryOutcome}</p></div><nav>{nav.map(item=><button key={item.id} className={page===item.id?'active':''} onClick={()=>setPage(item.id)}>{item.label}</button>)}</nav><div className="user"><strong>{app.user.name}</strong><span>{app.user.role}</span><small>{app.user.email}</small><button onClick={()=>{localStorage.removeItem(TOKEN);setApp(null);}}>Sign out</button></div></aside><main><header className="topbar"><span>{nav.find(x=>x.id===page)?.label}</span><strong className={app.ai.configured?'online':'offline'}>{app.ai.configured?`OpenRouter · ${app.ai.model}`:'OpenRouter not configured'}</strong></header><div className="content">{notice&&<div className={notice.type==='error'?'toast error':'toast'}>{notice.message}</div>}{page==='dashboard'&&data&&<Dashboard app={app} data={data} onOpen={openFeature}/>} {page==='analytics'&&<Analytics app={app} onOpen={openFeature}/>} {feature&&<Feature app={app} feature={feature} notify={notify}/>} {page==='audit'&&<Audit/>}</div></main></div>;
}
